contentColumnType: string
fieldGroup: bcb95be9-3b1b-4bbc-a7f3-ae788bb08586 # Common
handle: linkGroup
instructions: ''
name: 'Link Group'
searchable: false
settings:
  contentTable: '{{%matrixcontent_linkgroup}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
