contentColumnType: string
fieldGroup: bcb95be9-3b1b-4bbc-a7f3-ae788bb08586 # Common
handle: twoColumnCallout
instructions: ''
name: 'Two Column Callout'
searchable: false
settings:
  contentTable: '{{%matrixcontent_twocolumncallout}}'
  maxBlocks: '1'
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
