enableVersioning: true
handle: blogPosts
name: 'Blog Posts'
propagationMethod: all
siteSettings:
  c0320d98-8104-45b9-afef-72eb058731c4: # Craft CMS Demo
    enabledByDefault: true
    hasUrls: true
    template: pages/blogDetail
    uriFormat: 'blog/{slug}'
type: channel
